Updated pipeline

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -11,6 +11,7 @@ env:
   SRC_PATH: ./src
   CSPROJ_PATH: ./src/Reprise/Reprise.csproj
   UNIT_TESTS_PATH: ./tests/Reprise.UnitTests
+  MIN_COVERAGE: 90
   GIST_ID: 552110af4a546bfef6adfd60e60163c3
 
 jobs:
@@ -66,58 +67,6 @@ jobs:
         run: ./tools/dotnet-stryker --config-file stryker-config.yaml --reporter "html" --reporter "markdown"
         working-directory: ${{ env.UNIT_TESTS_PATH }}
 
-      - name: Extract coverage summary
-        id: coverage-summary
-        run: |
-          summary_message=""
-          set_output() {
-            if [[ -z $3 ]]; then
-              echo "::error::Got an empty value for $1."
-              exit 1
-            fi
-            echo "$1=$3$4" >> $GITHUB_OUTPUT
-            if [[ -n $2 ]]; then
-              summary_line="* $2: **$3$4**"
-              echo "$summary_line" >> $GITHUB_STEP_SUMMARY
-              summary_message+="$summary_line"
-              summary_message+=$'\n'
-            fi
-          }
-          set_lines_of_code() {
-            if [[ ${#1} -lt 3 ]]; then
-              set_output "lines_of_code" "Lines of code" "$1"
-            elif [[ ${#1} -eq 3 ]]; then
-              set_output "lines_of_code" "Lines of code" "0.${1::1}" "k"
-            elif [[ ${#1} -eq 4 ]]; then
-              set_output "lines_of_code" "Lines of code" "${1::1}.${1:1:1}" "k"
-            elif [[ ${#1} -eq 5 ]]; then
-              set_output "lines_of_code" "Lines of code" "${1:0:2}" "k"
-            else
-              echo "::error::Got an unsupported value $1 for lines_of_code."
-              exit 1
-            fi
-          }
-          set_color() {
-            if [[ $2 -ge 90 ]]; then
-              set_output "$1" "" "brightgreen"
-            elif [[ $2 -ge 70 ]]; then
-              set_output "$1" "" "yellow"
-            else
-              set_output "$1" "" "red"
-            fi
-          }
-          lines_of_code=$(cat ./TestCoverageReport/Summary.csv | grep -Po '(?<=Total lines:;)[0-9]+')
-          set_lines_of_code "$lines_of_code"
-          test_coverage=$(cat ./TestCoverageReport/Summary.csv | grep -Po '(?<=Line coverage:;)[0-9]{1,2}')
-          set_output "test_coverage" "Test coverage" "$test_coverage" "%"
-          set_color "test_coverage_color" "$test_coverage"
-          mutation_report_path=$(find ./StrykerOutput -name mutation-report.md)
-          mutation_score=$(cat $mutation_report_path | grep -Po '(?<=## The final mutation score is )[0-9]{1,2}')
-          set_output "mutation_score" "Mutation score" "$mutation_score" "%"
-          set_color "mutation_score_color" "$mutation_score"
-          set_output "summary_message" "" "$summary_message"
-        working-directory: ${{ env.UNIT_TESTS_PATH }}
-
       - name: Upload coverage report
         uses: actions/upload-artifact@v3
         with:
@@ -126,11 +75,47 @@ jobs:
             ${{ env.UNIT_TESTS_PATH }}/TestCoverageReport/
             ${{ env.UNIT_TESTS_PATH }}/StrykerOutput/
 
-      - name: Add coverage summary comment
-        if: ${{ github.event_name == 'pull_request' }}
-        uses: marocchino/sticky-pull-request-comment@v2
-        with:
-          message: ${{ steps.coverage-summary.outputs.summary_message }}
+      - name: Analyze coverage report
+        id: analyze-coverage-report
+        run: |
+          set_output() {
+            if [[ -z $3 ]]; then
+              echo "::error::Got an empty value for $1."
+              exit 1
+            fi
+            echo "$1=$3$4" >> $GITHUB_OUTPUT
+            echo "* $2: **$3$4**" >> $GITHUB_STEP_SUMMARY
+          }
+          set_lines_of_code() {
+            if [[ ${#1} -lt 4 ]]; then
+              set_output "lines_of_code" "Lines of code" "$1"
+            elif [[ ${#1} -eq 4 ]]; then
+              set_output "lines_of_code" "Lines of code" "${1::1}.${1:1:1}" "k"
+            elif [[ ${#1} -eq 5 ]]; then
+              set_output "lines_of_code" "Lines of code" "${1:0:2}" "k"
+            elif [[ ${#1} -eq 6 ]]; then
+              set_output "lines_of_code" "Lines of code" "${1:0:3}" "k"
+            else
+              echo "::error::Got an unsupported value $1 for lines_of_code."
+              exit 1
+            fi
+          }
+          check_coverage() {
+            if [[ $1 -lt ${{ env.MIN_COVERAGE }} || $2 -lt ${{ env.MIN_COVERAGE }} ]]; then
+              echo "" >> $GITHUB_STEP_SUMMARY
+              echo "**ERROR: The code coverage is insufficient.**" >> $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
+          }
+          lines_of_code=$(cat ./TestCoverageReport/Summary.csv | grep -Po '(?<=Total lines:;)[0-9]+')
+          set_lines_of_code "$lines_of_code"
+          test_coverage=$(cat ./TestCoverageReport/Summary.csv | grep -Po '(?<=Line coverage:;)[0-9]{1,2}')
+          set_output "test_coverage" "Test coverage" "$test_coverage" "%"
+          mutation_report_path=$(find ./StrykerOutput -name mutation-report.md)
+          mutation_score=$(cat $mutation_report_path | grep -Po '(?<=## The final mutation score is )[0-9]{1,2}')
+          set_output "mutation_score" "Mutation score" "$mutation_score" "%"
+          check_coverage "$test_coverage" "$mutation_score"
+        working-directory: ${{ env.UNIT_TESTS_PATH }}
 
       - name: Update lines of code gist
         if: ${{ github.event_name == 'push' }}
@@ -140,7 +125,7 @@ jobs:
           gistID: ${{ env.GIST_ID }}
           filename: lines-of-code.json
           label: loc
-          message: ${{ steps.coverage-summary.outputs.lines_of_code }}
+          message: ${{ steps.analyze-coverage-report.outputs.lines_of_code }}
           color: blue
 
       - name: Update coverage summary gist
@@ -151,8 +136,8 @@ jobs:
           gistID: ${{ env.GIST_ID }}
           filename: test-coverage.json
           label: test coverage
-          message: ${{ steps.coverage-summary.outputs.test_coverage }}
-          color: ${{ steps.coverage-summary.outputs.test_coverage_color }}
+          message: ${{ steps.analyze-coverage-report.outputs.test_coverage }}
+          color: brightgreen
 
       - name: Update mutation score gist
         if: ${{ github.event_name == 'push' }}
@@ -162,8 +147,8 @@ jobs:
           gistID: ${{ env.GIST_ID }}
           filename: mutation-score.json
           label: mutation score
-          message: ${{ steps.coverage-summary.outputs.mutation_score }}
-          color: ${{ steps.coverage-summary.outputs.mutation_score_color }}
+          message: ${{ steps.analyze-coverage-report.outputs.mutation_score }}
+          color: brightgreen
 
       - name: Check publish conditions
         if: ${{ github.event_name == 'push' }}
